### ISSUE TITLE
I'd like to get your github username :)

### ISSUE THREAD

**Issue by mehtamanan** [manan/Virtism#1]
Hello @manan

As you may have noticed, we share the same name and I'd love to get your username if you're not using it :)

Feel free to contact me at on linkedin.com/in/mehta-manan to discuss!

**Comment by mehtamanan** [comment]
@manan any thoughts so far? :)

**Comment by manan** [comment]
Hi Mehta,

I have just started data science programming and will start using the name.

What are you willing to offer.

Thanks
Manan

**Comment by mehtamanan** [comment]
Hey, that's great! Do you want to shoot me an email at manan.shm@gmail.com? Happy to work something out :)

**Comment by mehtamanan** [comment]
@manan hey, let me know if you'd like to move forward! feel free to email me or message me on linkedin.

**Comment by mehtamanan** [comment]
@manan could you let me know if you're not interested in the exchange? i'm happy to make it work for the both of us but want to close this this week.
